version: '3.9'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - client
    networks:
      - app-network

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./server
    ports:
      - "3002:3000"
    depends_on:
      - db
    env_file:
      - ./server/.env
    networks:
      - app-network
  
  client:
    build: ./client
    ports:
      - "3003:3000"
    depends_on:
      - db
    env_file:
      - ./client/.env
    networks:
      - app-network
volumes:
  db:

networks:
  app-network:
    driver: bridge
